### ISSUE TITLE
Improvement in highway hero game

### ISSUE THREAD

**Issue by rishibaghel25** [rishibaghel25/2DChampion#11]
Make a better start screen and add a play/pause button 
![ss1](https://github.com/rishibaghel25/2DChampion/assets/100260148/0414744a-b842-486b-9d9a-b0b4fb414ea3)

**Comment by SuriyaaVijay** [comment]
I will improve the overall UI of the game along with the landing page. Assign me this task

**Comment by rishibaghel25** [comment]
Lets see . I've assigned the task
